// <auto-generated />
using System;
using Commerzia_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Commerzia_API.Migrations
{
    [DbContext(typeof(CommerziaContext))]
    partial class CommerziaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Commerzia_API.Models.ActivoFijo", b =>
                {
                    b.Property<int>("IdActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdActivo"));

                    b.Property<string>("CodigoActivo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly>("FechaAdquisicion")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdCuentaActivo")
                        .HasColumnType("int");

                    b.Property<int?>("IdCuentaDepreciacion")
                        .HasColumnType("int");

                    b.Property<int?>("IdCuentaGasto")
                        .HasColumnType("int");

                    b.Property<int?>("IdEstado")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("ValorAdquisicion")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("ValorResidual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("VidaUtilMeses")
                        .HasColumnType("int");

                    b.HasKey("IdActivo")
                        .HasName("PK__ActivoFi__146481C0DD3BC655");

                    b.HasIndex("IdCuentaActivo");

                    b.HasIndex("IdCuentaDepreciacion");

                    b.HasIndex("IdCuentaGasto");

                    b.HasIndex("IdEstado");

                    b.ToTable("ActivoFijo", (string)null);
                });

            modelBuilder.Entity("Commerzia_API.Models.Asiento", b =>
                {
                    b.Property<int>("IdAsiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAsiento"));

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Glosa")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("IdEstado")
                        .HasColumnType("int");

                    b.Property<int>("IdPeriodo")
                        .HasColumnType("int");

                    b.Property<int?>("IdTipoDocumento")
                        .HasColumnType("int");

                    b.Property<string>("NumeroAsiento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdAsiento")
                        .HasName("PK__Asiento__F567872146099DEB");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdPeriodo");

                    b.HasIndex("IdTipoDocumento");

                    b.ToTable("Asiento", (string)null);
                });

            modelBuilder.Entity("Commerzia_API.Models.AsientoDetalle", b =>
                {
                    b.Property<int>("IdAsientoDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAsientoDetalle"));

                    b.Property<decimal?>("Debe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Haber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("IdAsiento")
                        .HasColumnType("int");

                    b.Property<int>("IdCuenta")
                        .HasColumnType("int");

                    b.Property<string>("Referencia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdAsientoDetalle")
                        .HasName("PK__AsientoD__984DDE920B9D85B0");

                    b.HasIndex("IdAsiento");

                    b.HasIndex("IdCuenta");

                    b.ToTable("AsientoDetalle", (string)null);
                });

            modelBuilder.Entity("Commerzia_API.Models.Categorium", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdCategoria")
                        .HasName("PK__Categori__A3C02A10F365E64F");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("Commerzia_API.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Correo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DocumentoIdentidad")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdEstado")
                        .HasColumnType("int");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdCliente")
                        .HasName("PK__Cliente__D594664229FCDACA");

                    b.HasIndex("IdEstado");

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("Commerzia_API.Models.CobroCliente", b =>
                {
                    b.Property<int>("IdCobro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCobro"));

                    b.Property<DateTime?>("FechaCobro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdAsiento")
                        .HasColumnType("int");

                    b.Property<int>("IdFormaPago")
                        .HasColumnType("int");

                    b.Property<int>("IdVenta")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("NumeroReferencia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdCobro")
                        .HasName("PK__CobroCli__D0B0CD00314ABF45");

                    b.HasIndex("IdAsiento");

                    b.HasIndex("IdFormaPago");

                    b.HasIndex("IdVenta");

                    b.ToTable("CobroCliente", (string)null);
                });

            modelBuilder.Entity("Commerzia_API.Models.Compra", b =>
                {
                    b.Property<int>("IdCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCompra"));

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly>("FechaEmision")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRecepcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdAsiento")
                        .HasColumnType("int");

                    b.Property<int?>("IdEstado")
                        .HasColumnType("int");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("int");

                    b.Property<decimal?>("Impuestos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("NumeroFactura")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("SaldoPendiente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("SubTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("Total")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdCompra")
                        .HasName("PK__Compra__0A5CDB5C380B9542");

                    b.HasIndex("IdAsiento");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdProveedor");

                    b.ToTable("Compra", (string)null);
                });

            modelBuilder.Entity("Commerzia_API.Models.CompraDetalle", b =>
                {
                    b.Property<int>("IdCompraDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCompraDetalle"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("CostoUnitario")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCompra")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalLinea")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdCompraDetalle")
                        .HasName("PK__CompraDe__A1B840C502553A2E");

                    b.HasIndex("IdCompra");

                    b.HasIndex("IdProducto");

                    b.ToTable("CompraDetalle", (string)null);
                });

            modelBuilder.Entity("Commerzia_API.Models.CuentaContable", b =>
                {
                    b.Property<int>("IdCuenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCuenta"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool?>("EsCuentaMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdCuentaPadre")
                        .HasColumnType("int");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdCuenta")
                        .HasName("PK__CuentaCo__D41FD70665D9FE74");

                    b.HasIndex("IdCuentaPadre");

                    b.HasIndex(new[] { "Codigo" }, "UQ__CuentaCo__06370DAC8971D129")
                        .IsUnique();

                    b.ToTable("CuentaContable", (string)null);
                });

            modelBuilder.Entity("Commerzia_API.Models.DepreciacionActivo", b =>
                {
                    b.Property<int>("IdDepreciacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDepreciacion"));

                    b.Property<DateOnly>("FechaCalculo")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdActivo")
                        .HasColumnType("int");

                    b.Property<int?>("IdAsiento")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoDepreciado")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("ValorLibroRemanente")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("IdDepreciacion")
                        .HasName("PK__Deprecia__64EADB742DAE95ED");

                    b.HasIndex("IdActivo");

                    b.HasIndex("IdAsiento");

                    b.ToTable("DepreciacionActivo", (string)null);
                });

            modelBuilder.Entity("Commerzia_API.Models.DevolucionVentaDetalle", b =>
                {
                    b.Property<int>("IdDevolucionDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDevolucionDetalle"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdDevolucion")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<int?>("IdVentaDetalle")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TotalLinea")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdDevolucionDetalle")
                        .HasName("PK__Devoluci__ADB5A41C94FAD61F");

                    b.HasIndex("IdDevolucion");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdVentaDetalle");

                    b.ToTable("DevolucionVentaDetalle", (string)null);
                });

            modelBuilder.Entity("Commerzia_API.Models.DevolucionVentum", b =>
                {
                    b.Property<int>("IdDevolucion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDevolucion"));

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaDevolucion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdAsiento")
                        .HasColumnType("int");

                    b.Property<int?>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<int?>("IdEstado")
                        .HasColumnType("int");

                    b.Property<int>("IdVenta")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NumeroNotaCredito")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalDevuelto")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdDevolucion")
                        .HasName("PK__Devoluci__7B3585A2E46478DB");

                    b.HasIndex("IdAsiento");

                    b.HasIndex("IdEmpleado");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdVenta");

                    b.ToTable("DevolucionVenta");
                });

            modelBuilder.Entity("Commerzia_API.Models.Empleado", b =>
                {
                    b.Property<int>("IdEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpleado"));

                    b.Property<string>("Cargo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Correo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("FechaContratacion")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdEstado")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdEmpleado")
                        .HasName("PK__Empleado__CE6D8B9E6AF86C6E");

                    b.HasIndex("IdEstado");

                    b.ToTable("Empleado", (string)null);
                });

            modelBuilder.Entity("Commerzia_API.Models.Estado", b =>
                {
                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstado"));

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Modulo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdEstado")
                        .HasName("PK__Estado__FBB0EDC19E17FE01");

                    b.ToTable("Estado", (string)null);
                });

            modelBuilder.Entity("Commerzia_API.Models.FormaPago", b =>
                {
                    b.Property<int>("IdFormaPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFormaPago"));

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdFormaPago")
                        .HasName("PK__FormaPag__C777CA684F96B044");

                    b.ToTable("FormaPago", (string)null);
                });

            modelBuilder.Entity("Commerzia_API.Models.Gasto", b =>
                {
                    b.Property<int>("IdGasto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGasto"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaGasto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdAsiento")
                        .HasColumnType("int");

                    b.Property<int?>("IdEstado")
                        .HasColumnType("int");

                    b.Property<int>("IdFormaPago")
                        .HasColumnType("int");

                    b.Property<int?>("IdProveedor")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("NumeroComprobante")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdGasto")
                        .HasName("PK__Gasto__C630244D597F453B");

                    b.HasIndex("IdAsiento");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdFormaPago");

                    b.HasIndex("IdProveedor");

                    b.ToTable("Gasto", (string)null);
                });

            modelBuilder.Entity("Commerzia_API.Models.Marca", b =>
                {
                    b.Property<int>("IdMarca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMarca"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdMarca")
                        .HasName("PK__Marca__4076A887429E9CF9");

                    b.ToTable("Marca", (string)null);
                });

            modelBuilder.Entity("Commerzia_API.Models.MovimientoInventario", b =>
                {
                    b.Property<int>("IdMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMovimiento"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal?>("CostoUnitario")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<DateTime?>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdCompra")
                        .HasColumnType("int");

                    b.Property<int?>("IdDevolucion")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoMovimiento")
                        .HasColumnType("int");

                    b.Property<int?>("IdVenta")
                        .HasColumnType("int");

                    b.Property<int>("SaldoCantidad")
                        .HasColumnType("int");

                    b.Property<decimal?>("SaldoCostoTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdMovimiento")
                        .HasName("PK__Movimien__881A6AE0FB64E25D");

                    b.HasIndex("IdCompra");

                    b.HasIndex("IdDevolucion");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdTipoMovimiento");

                    b.HasIndex("IdVenta");

                    b.ToTable("MovimientoInventario", (string)null);
                });

            modelBuilder.Entity("Commerzia_API.Models.PagoProveedor", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPago"));

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdAsiento")
                        .HasColumnType("int");

                    b.Property<int>("IdCompra")
                        .HasColumnType("int");

                    b.Property<int>("IdFormaPago")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("NumeroReferencia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdPago")
                        .HasName("PK__PagoProv__FC851A3ADAB2C9A9");

                    b.HasIndex("IdAsiento");

                    b.HasIndex("IdCompra");

                    b.HasIndex("IdFormaPago");

                    b.ToTable("PagoProveedor", (string)null);
                });

            modelBuilder.Entity("Commerzia_API.Models.PeriodoContable", b =>
                {
                    b.Property<int>("IdPeriodo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPeriodo"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<bool?>("Cerrado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdPeriodo")
                        .HasName("PK__PeriodoC__B44699FE534B3628");

                    b.ToTable("PeriodoContable", (string)null);
                });

            modelBuilder.Entity("Commerzia_API.Models.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<string>("CodigoSku")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CodigoSKU");

                    b.Property<decimal?>("CostoPromedio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 4)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<int?>("IdEstado")
                        .HasColumnType("int");

                    b.Property<int?>("IdMarca")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdProducto")
                        .HasName("PK__Producto__09889210931CA8C5");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdMarca");

                    b.HasIndex(new[] { "CodigoSku" }, "UQ__Producto__F02F03F986E8036F")
                        .IsUnique()
                        .HasFilter("[CodigoSKU] IS NOT NULL");

                    b.ToTable("Producto", (string)null);
                });

            modelBuilder.Entity("Commerzia_API.Models.Proveedor", b =>
                {
                    b.Property<int>("IdProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProveedor"));

                    b.Property<string>("Correo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DocumentoIdentidad")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdEstado")
                        .HasColumnType("int");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdProveedor")
                        .HasName("PK__Proveedo__E8B631AFA3EC6526");

                    b.HasIndex("IdEstado");

                    b.ToTable("Proveedor", (string)null);
                });

            modelBuilder.Entity("Commerzia_API.Models.TipoDocumento", b =>
                {
                    b.Property<int>("IdTipoDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoDocumento"));

                    b.Property<string>("CodigoFiscal")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdTipoDocumento")
                        .HasName("PK__TipoDocu__3AB3332F235FE0C8");

                    b.ToTable("TipoDocumento", (string)null);
                });

            modelBuilder.Entity("Commerzia_API.Models.TipoMovimientoInventario", b =>
                {
                    b.Property<int>("IdTipoMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoMovimiento"));

                    b.Property<bool>("EsEntrada")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdTipoMovimiento")
                        .HasName("PK__TipoMovi__820D7FC282BEEF2E");

                    b.ToTable("TipoMovimientoInventario", (string)null);
                });

            modelBuilder.Entity("Commerzia_API.Models.VentaDetalle", b =>
                {
                    b.Property<int>("IdVentaDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVentaDetalle"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal?>("Descuento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<int>("IdVenta")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TotalLinea")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdVentaDetalle")
                        .HasName("PK__VentaDet__2787211D5A62EC0F");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdVenta");

                    b.ToTable("VentaDetalle", (string)null);
                });

            modelBuilder.Entity("Commerzia_API.Models.Ventum", b =>
                {
                    b.Property<int>("IdVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVenta"));

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdAsiento")
                        .HasColumnType("int");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<int?>("IdEstado")
                        .HasColumnType("int");

                    b.Property<decimal?>("Impuestos")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("NumeroComprobante")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("SaldoPendiente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("SubTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("Total")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdVenta")
                        .HasName("PK__Venta__BC1240BD74160A58");

                    b.HasIndex("IdAsiento");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdEmpleado");

                    b.HasIndex("IdEstado");

                    b.ToTable("Venta");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Commerzia_API.Models.ActivoFijo", b =>
                {
                    b.HasOne("Commerzia_API.Models.CuentaContable", "IdCuentaActivoNavigation")
                        .WithMany("ActivoFijoIdCuentaActivoNavigations")
                        .HasForeignKey("IdCuentaActivo")
                        .HasConstraintName("FK_Activo_CtaActivo");

                    b.HasOne("Commerzia_API.Models.CuentaContable", "IdCuentaDepreciacionNavigation")
                        .WithMany("ActivoFijoIdCuentaDepreciacionNavigations")
                        .HasForeignKey("IdCuentaDepreciacion")
                        .HasConstraintName("FK_Activo_CtaDeprec");

                    b.HasOne("Commerzia_API.Models.CuentaContable", "IdCuentaGastoNavigation")
                        .WithMany("ActivoFijoIdCuentaGastoNavigations")
                        .HasForeignKey("IdCuentaGasto")
                        .HasConstraintName("FK_Activo_CtaGasto");

                    b.HasOne("Commerzia_API.Models.Estado", "IdEstadoNavigation")
                        .WithMany("ActivoFijos")
                        .HasForeignKey("IdEstado")
                        .HasConstraintName("FK_Activo_Estado");

                    b.Navigation("IdCuentaActivoNavigation");

                    b.Navigation("IdCuentaDepreciacionNavigation");

                    b.Navigation("IdCuentaGastoNavigation");

                    b.Navigation("IdEstadoNavigation");
                });

            modelBuilder.Entity("Commerzia_API.Models.Asiento", b =>
                {
                    b.HasOne("Commerzia_API.Models.Estado", "IdEstadoNavigation")
                        .WithMany("Asientos")
                        .HasForeignKey("IdEstado")
                        .HasConstraintName("FK_Asiento_Estado");

                    b.HasOne("Commerzia_API.Models.PeriodoContable", "IdPeriodoNavigation")
                        .WithMany("Asientos")
                        .HasForeignKey("IdPeriodo")
                        .IsRequired()
                        .HasConstraintName("FK_Asiento_Periodo");

                    b.HasOne("Commerzia_API.Models.TipoDocumento", "IdTipoDocumentoNavigation")
                        .WithMany("Asientos")
                        .HasForeignKey("IdTipoDocumento")
                        .HasConstraintName("FK_Asiento_TipoDoc");

                    b.Navigation("IdEstadoNavigation");

                    b.Navigation("IdPeriodoNavigation");

                    b.Navigation("IdTipoDocumentoNavigation");
                });

            modelBuilder.Entity("Commerzia_API.Models.AsientoDetalle", b =>
                {
                    b.HasOne("Commerzia_API.Models.Asiento", "IdAsientoNavigation")
                        .WithMany("AsientoDetalles")
                        .HasForeignKey("IdAsiento")
                        .IsRequired()
                        .HasConstraintName("FK_AsientoDet_Asiento");

                    b.HasOne("Commerzia_API.Models.CuentaContable", "IdCuentaNavigation")
                        .WithMany("AsientoDetalles")
                        .HasForeignKey("IdCuenta")
                        .IsRequired()
                        .HasConstraintName("FK_AsientoDet_Cuenta");

                    b.Navigation("IdAsientoNavigation");

                    b.Navigation("IdCuentaNavigation");
                });

            modelBuilder.Entity("Commerzia_API.Models.Cliente", b =>
                {
                    b.HasOne("Commerzia_API.Models.Estado", "IdEstadoNavigation")
                        .WithMany("Clientes")
                        .HasForeignKey("IdEstado")
                        .HasConstraintName("FK_Cliente_Estado");

                    b.Navigation("IdEstadoNavigation");
                });

            modelBuilder.Entity("Commerzia_API.Models.CobroCliente", b =>
                {
                    b.HasOne("Commerzia_API.Models.Asiento", "IdAsientoNavigation")
                        .WithMany("CobroClientes")
                        .HasForeignKey("IdAsiento")
                        .HasConstraintName("FK_Cobro_Asiento");

                    b.HasOne("Commerzia_API.Models.FormaPago", "IdFormaPagoNavigation")
                        .WithMany("CobroClientes")
                        .HasForeignKey("IdFormaPago")
                        .IsRequired()
                        .HasConstraintName("FK_Cobro_FormaPago");

                    b.HasOne("Commerzia_API.Models.Ventum", "IdVentaNavigation")
                        .WithMany("CobroClientes")
                        .HasForeignKey("IdVenta")
                        .IsRequired()
                        .HasConstraintName("FK_Cobro_Venta");

                    b.Navigation("IdAsientoNavigation");

                    b.Navigation("IdFormaPagoNavigation");

                    b.Navigation("IdVentaNavigation");
                });

            modelBuilder.Entity("Commerzia_API.Models.Compra", b =>
                {
                    b.HasOne("Commerzia_API.Models.Asiento", "IdAsientoNavigation")
                        .WithMany("Compras")
                        .HasForeignKey("IdAsiento")
                        .HasConstraintName("FK_Compra_Asiento");

                    b.HasOne("Commerzia_API.Models.Estado", "IdEstadoNavigation")
                        .WithMany("Compras")
                        .HasForeignKey("IdEstado")
                        .HasConstraintName("FK_Compra_Estado");

                    b.HasOne("Commerzia_API.Models.Proveedor", "IdProveedorNavigation")
                        .WithMany("Compras")
                        .HasForeignKey("IdProveedor")
                        .IsRequired()
                        .HasConstraintName("FK_Compra_Proveedor");

                    b.Navigation("IdAsientoNavigation");

                    b.Navigation("IdEstadoNavigation");

                    b.Navigation("IdProveedorNavigation");
                });

            modelBuilder.Entity("Commerzia_API.Models.CompraDetalle", b =>
                {
                    b.HasOne("Commerzia_API.Models.Compra", "IdCompraNavigation")
                        .WithMany("CompraDetalles")
                        .HasForeignKey("IdCompra")
                        .IsRequired()
                        .HasConstraintName("FK_CompraDet_Compra");

                    b.HasOne("Commerzia_API.Models.Producto", "IdProductoNavigation")
                        .WithMany("CompraDetalles")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK_CompraDet_Producto");

                    b.Navigation("IdCompraNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("Commerzia_API.Models.CuentaContable", b =>
                {
                    b.HasOne("Commerzia_API.Models.CuentaContable", "IdCuentaPadreNavigation")
                        .WithMany("InverseIdCuentaPadreNavigation")
                        .HasForeignKey("IdCuentaPadre")
                        .HasConstraintName("FK_Cuenta_Padre");

                    b.Navigation("IdCuentaPadreNavigation");
                });

            modelBuilder.Entity("Commerzia_API.Models.DepreciacionActivo", b =>
                {
                    b.HasOne("Commerzia_API.Models.ActivoFijo", "IdActivoNavigation")
                        .WithMany("DepreciacionActivos")
                        .HasForeignKey("IdActivo")
                        .IsRequired()
                        .HasConstraintName("FK_Deprec_Activo");

                    b.HasOne("Commerzia_API.Models.Asiento", "IdAsientoNavigation")
                        .WithMany("DepreciacionActivos")
                        .HasForeignKey("IdAsiento")
                        .HasConstraintName("FK_Deprec_Asiento");

                    b.Navigation("IdActivoNavigation");

                    b.Navigation("IdAsientoNavigation");
                });

            modelBuilder.Entity("Commerzia_API.Models.DevolucionVentaDetalle", b =>
                {
                    b.HasOne("Commerzia_API.Models.DevolucionVentum", "IdDevolucionNavigation")
                        .WithMany("DevolucionVentaDetalles")
                        .HasForeignKey("IdDevolucion")
                        .IsRequired()
                        .HasConstraintName("FK_DevDet_Devolucion");

                    b.HasOne("Commerzia_API.Models.Producto", "IdProductoNavigation")
                        .WithMany("DevolucionVentaDetalles")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK_DevDet_Producto");

                    b.HasOne("Commerzia_API.Models.VentaDetalle", "IdVentaDetalleNavigation")
                        .WithMany("DevolucionVentaDetalles")
                        .HasForeignKey("IdVentaDetalle")
                        .HasConstraintName("FK_DevDet_VentaDetalle");

                    b.Navigation("IdDevolucionNavigation");

                    b.Navigation("IdProductoNavigation");

                    b.Navigation("IdVentaDetalleNavigation");
                });

            modelBuilder.Entity("Commerzia_API.Models.DevolucionVentum", b =>
                {
                    b.HasOne("Commerzia_API.Models.Asiento", "IdAsientoNavigation")
                        .WithMany("DevolucionVenta")
                        .HasForeignKey("IdAsiento")
                        .HasConstraintName("FK_Devolucion_Asiento");

                    b.HasOne("Commerzia_API.Models.Empleado", "IdEmpleadoNavigation")
                        .WithMany("DevolucionVenta")
                        .HasForeignKey("IdEmpleado")
                        .HasConstraintName("FK_Devolucion_Empleado");

                    b.HasOne("Commerzia_API.Models.Estado", "IdEstadoNavigation")
                        .WithMany("DevolucionVenta")
                        .HasForeignKey("IdEstado")
                        .HasConstraintName("FK_Devolucion_Estado");

                    b.HasOne("Commerzia_API.Models.Ventum", "IdVentaNavigation")
                        .WithMany("DevolucionVenta")
                        .HasForeignKey("IdVenta")
                        .IsRequired()
                        .HasConstraintName("FK_Devolucion_Venta");

                    b.Navigation("IdAsientoNavigation");

                    b.Navigation("IdEmpleadoNavigation");

                    b.Navigation("IdEstadoNavigation");

                    b.Navigation("IdVentaNavigation");
                });

            modelBuilder.Entity("Commerzia_API.Models.Empleado", b =>
                {
                    b.HasOne("Commerzia_API.Models.Estado", "IdEstadoNavigation")
                        .WithMany("Empleados")
                        .HasForeignKey("IdEstado")
                        .HasConstraintName("FK_Empleado_Estado");

                    b.Navigation("IdEstadoNavigation");
                });

            modelBuilder.Entity("Commerzia_API.Models.Gasto", b =>
                {
                    b.HasOne("Commerzia_API.Models.Asiento", "IdAsientoNavigation")
                        .WithMany("Gastos")
                        .HasForeignKey("IdAsiento")
                        .HasConstraintName("FK_Gasto_Asiento");

                    b.HasOne("Commerzia_API.Models.Estado", "IdEstadoNavigation")
                        .WithMany("Gastos")
                        .HasForeignKey("IdEstado")
                        .HasConstraintName("FK_Gasto_Estado");

                    b.HasOne("Commerzia_API.Models.FormaPago", "IdFormaPagoNavigation")
                        .WithMany("Gastos")
                        .HasForeignKey("IdFormaPago")
                        .IsRequired()
                        .HasConstraintName("FK_Gasto_FormaPago");

                    b.HasOne("Commerzia_API.Models.Proveedor", "IdProveedorNavigation")
                        .WithMany("Gastos")
                        .HasForeignKey("IdProveedor")
                        .HasConstraintName("FK_Gasto_Proveedor");

                    b.Navigation("IdAsientoNavigation");

                    b.Navigation("IdEstadoNavigation");

                    b.Navigation("IdFormaPagoNavigation");

                    b.Navigation("IdProveedorNavigation");
                });

            modelBuilder.Entity("Commerzia_API.Models.MovimientoInventario", b =>
                {
                    b.HasOne("Commerzia_API.Models.Compra", "IdCompraNavigation")
                        .WithMany("MovimientoInventarios")
                        .HasForeignKey("IdCompra")
                        .HasConstraintName("FK_MovInv_Compra");

                    b.HasOne("Commerzia_API.Models.DevolucionVentum", "IdDevolucionNavigation")
                        .WithMany("MovimientoInventarios")
                        .HasForeignKey("IdDevolucion")
                        .HasConstraintName("FK_MovInv_Devolucion");

                    b.HasOne("Commerzia_API.Models.Producto", "IdProductoNavigation")
                        .WithMany("MovimientoInventarios")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK_MovInv_Producto");

                    b.HasOne("Commerzia_API.Models.TipoMovimientoInventario", "IdTipoMovimientoNavigation")
                        .WithMany("MovimientoInventarios")
                        .HasForeignKey("IdTipoMovimiento")
                        .IsRequired()
                        .HasConstraintName("FK_MovInv_TipoMov");

                    b.HasOne("Commerzia_API.Models.Ventum", "IdVentaNavigation")
                        .WithMany("MovimientoInventarios")
                        .HasForeignKey("IdVenta")
                        .HasConstraintName("FK_MovInv_Venta");

                    b.Navigation("IdCompraNavigation");

                    b.Navigation("IdDevolucionNavigation");

                    b.Navigation("IdProductoNavigation");

                    b.Navigation("IdTipoMovimientoNavigation");

                    b.Navigation("IdVentaNavigation");
                });

            modelBuilder.Entity("Commerzia_API.Models.PagoProveedor", b =>
                {
                    b.HasOne("Commerzia_API.Models.Asiento", "IdAsientoNavigation")
                        .WithMany("PagoProveedors")
                        .HasForeignKey("IdAsiento")
                        .HasConstraintName("FK_PagoProv_Asiento");

                    b.HasOne("Commerzia_API.Models.Compra", "IdCompraNavigation")
                        .WithMany("PagoProveedors")
                        .HasForeignKey("IdCompra")
                        .IsRequired()
                        .HasConstraintName("FK_PagoProv_Compra");

                    b.HasOne("Commerzia_API.Models.FormaPago", "IdFormaPagoNavigation")
                        .WithMany("PagoProveedors")
                        .HasForeignKey("IdFormaPago")
                        .IsRequired()
                        .HasConstraintName("FK_PagoProv_FormaPago");

                    b.Navigation("IdAsientoNavigation");

                    b.Navigation("IdCompraNavigation");

                    b.Navigation("IdFormaPagoNavigation");
                });

            modelBuilder.Entity("Commerzia_API.Models.Producto", b =>
                {
                    b.HasOne("Commerzia_API.Models.Categorium", "IdCategoriaNavigation")
                        .WithMany("Productos")
                        .HasForeignKey("IdCategoria")
                        .HasConstraintName("FK_Producto_Categoria");

                    b.HasOne("Commerzia_API.Models.Estado", "IdEstadoNavigation")
                        .WithMany("Productos")
                        .HasForeignKey("IdEstado")
                        .HasConstraintName("FK_Producto_Estado");

                    b.HasOne("Commerzia_API.Models.Marca", "IdMarcaNavigation")
                        .WithMany("Productos")
                        .HasForeignKey("IdMarca")
                        .HasConstraintName("FK_Producto_Marca");

                    b.Navigation("IdCategoriaNavigation");

                    b.Navigation("IdEstadoNavigation");

                    b.Navigation("IdMarcaNavigation");
                });

            modelBuilder.Entity("Commerzia_API.Models.Proveedor", b =>
                {
                    b.HasOne("Commerzia_API.Models.Estado", "IdEstadoNavigation")
                        .WithMany("Proveedors")
                        .HasForeignKey("IdEstado")
                        .HasConstraintName("FK_Proveedor_Estado");

                    b.Navigation("IdEstadoNavigation");
                });

            modelBuilder.Entity("Commerzia_API.Models.VentaDetalle", b =>
                {
                    b.HasOne("Commerzia_API.Models.Producto", "IdProductoNavigation")
                        .WithMany("VentaDetalles")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK_VentaDet_Producto");

                    b.HasOne("Commerzia_API.Models.Ventum", "IdVentaNavigation")
                        .WithMany("VentaDetalles")
                        .HasForeignKey("IdVenta")
                        .IsRequired()
                        .HasConstraintName("FK_VentaDet_Venta");

                    b.Navigation("IdProductoNavigation");

                    b.Navigation("IdVentaNavigation");
                });

            modelBuilder.Entity("Commerzia_API.Models.Ventum", b =>
                {
                    b.HasOne("Commerzia_API.Models.Asiento", "IdAsientoNavigation")
                        .WithMany("Venta")
                        .HasForeignKey("IdAsiento")
                        .HasConstraintName("FK_Venta_Asiento");

                    b.HasOne("Commerzia_API.Models.Cliente", "IdClienteNavigation")
                        .WithMany("Venta")
                        .HasForeignKey("IdCliente")
                        .IsRequired()
                        .HasConstraintName("FK_Venta_Cliente");

                    b.HasOne("Commerzia_API.Models.Empleado", "IdEmpleadoNavigation")
                        .WithMany("Venta")
                        .HasForeignKey("IdEmpleado")
                        .IsRequired()
                        .HasConstraintName("FK_Venta_Empleado");

                    b.HasOne("Commerzia_API.Models.Estado", "IdEstadoNavigation")
                        .WithMany("Venta")
                        .HasForeignKey("IdEstado")
                        .HasConstraintName("FK_Venta_Estado");

                    b.Navigation("IdAsientoNavigation");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdEmpleadoNavigation");

                    b.Navigation("IdEstadoNavigation");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Commerzia_API.Models.ActivoFijo", b =>
                {
                    b.Navigation("DepreciacionActivos");
                });

            modelBuilder.Entity("Commerzia_API.Models.Asiento", b =>
                {
                    b.Navigation("AsientoDetalles");

                    b.Navigation("CobroClientes");

                    b.Navigation("Compras");

                    b.Navigation("DepreciacionActivos");

                    b.Navigation("DevolucionVenta");

                    b.Navigation("Gastos");

                    b.Navigation("PagoProveedors");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Commerzia_API.Models.Categorium", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Commerzia_API.Models.Cliente", b =>
                {
                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Commerzia_API.Models.Compra", b =>
                {
                    b.Navigation("CompraDetalles");

                    b.Navigation("MovimientoInventarios");

                    b.Navigation("PagoProveedors");
                });

            modelBuilder.Entity("Commerzia_API.Models.CuentaContable", b =>
                {
                    b.Navigation("ActivoFijoIdCuentaActivoNavigations");

                    b.Navigation("ActivoFijoIdCuentaDepreciacionNavigations");

                    b.Navigation("ActivoFijoIdCuentaGastoNavigations");

                    b.Navigation("AsientoDetalles");

                    b.Navigation("InverseIdCuentaPadreNavigation");
                });

            modelBuilder.Entity("Commerzia_API.Models.DevolucionVentum", b =>
                {
                    b.Navigation("DevolucionVentaDetalles");

                    b.Navigation("MovimientoInventarios");
                });

            modelBuilder.Entity("Commerzia_API.Models.Empleado", b =>
                {
                    b.Navigation("DevolucionVenta");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Commerzia_API.Models.Estado", b =>
                {
                    b.Navigation("ActivoFijos");

                    b.Navigation("Asientos");

                    b.Navigation("Clientes");

                    b.Navigation("Compras");

                    b.Navigation("DevolucionVenta");

                    b.Navigation("Empleados");

                    b.Navigation("Gastos");

                    b.Navigation("Productos");

                    b.Navigation("Proveedors");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Commerzia_API.Models.FormaPago", b =>
                {
                    b.Navigation("CobroClientes");

                    b.Navigation("Gastos");

                    b.Navigation("PagoProveedors");
                });

            modelBuilder.Entity("Commerzia_API.Models.Marca", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Commerzia_API.Models.PeriodoContable", b =>
                {
                    b.Navigation("Asientos");
                });

            modelBuilder.Entity("Commerzia_API.Models.Producto", b =>
                {
                    b.Navigation("CompraDetalles");

                    b.Navigation("DevolucionVentaDetalles");

                    b.Navigation("MovimientoInventarios");

                    b.Navigation("VentaDetalles");
                });

            modelBuilder.Entity("Commerzia_API.Models.Proveedor", b =>
                {
                    b.Navigation("Compras");

                    b.Navigation("Gastos");
                });

            modelBuilder.Entity("Commerzia_API.Models.TipoDocumento", b =>
                {
                    b.Navigation("Asientos");
                });

            modelBuilder.Entity("Commerzia_API.Models.TipoMovimientoInventario", b =>
                {
                    b.Navigation("MovimientoInventarios");
                });

            modelBuilder.Entity("Commerzia_API.Models.VentaDetalle", b =>
                {
                    b.Navigation("DevolucionVentaDetalles");
                });

            modelBuilder.Entity("Commerzia_API.Models.Ventum", b =>
                {
                    b.Navigation("CobroClientes");

                    b.Navigation("DevolucionVenta");

                    b.Navigation("MovimientoInventarios");

                    b.Navigation("VentaDetalles");
                });
#pragma warning restore 612, 618
        }
    }
}
